#!/bin/bash
chmod u+x redis01.sh
chmod u+x redis02.sh
chmod u+x redis03.sh
chmod u+x redis04.sh
chmod u+x redis05.sh
chmod u+x redis06.sh
chmod u+x redis07.sh
chmod u+x redis08.sh
chmod u+x redis09.sh
chmod u+x redis10.sh
chmod u+x database01.sh
chmod u+x database02.sh
chmod u+x proxy01.sh
chmod u+x service01.sh
chmod u+x service02.sh
chmod u+x service03.sh
chmod u+x service04.sh
chmod u+x service05.sh
chmod u+x service06.sh
chmod u+x service07.sh
chmod u+x service08.sh
chmod u+x service09.sh
chmod u+x service10.sh
chmod u+x nginx01.sh